proxy_cache_path /var/cache/nginx/app_go   levels=1:2 keys_zone=cache_go:10m     max_size=100m inactive=30s  use_temp_path=off;
proxy_cache_path /var/cache/nginx/app_python levels=1:2 keys_zone=cache_python:10m max_size=100m inactive=2m   use_temp_path=off;

# ─── Rate limiting (10 req/s por IP, burst 20) ───────────
limit_req_zone $binary_remote_addr zone=global_limit:10m rate=10r/s;

log_format cache_log '$remote_addr - [$time_local] "$request" $status '
                     'cache=$upstream_cache_status rt=$request_time '
                     'upstream=$upstream_response_time';

# ─── App Go (cache 10s) ──────────────────────────────────
server {
    listen 80;
    server_name localhost;
    server_tokens off;

    # ── Security Headers ──
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-Frame-Options "DENY" always;
    add_header X-XSS-Protection "1; mode=block" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;
    add_header Content-Security-Policy "default-src 'self'" always;

    access_log /var/log/nginx/app_go_access.log cache_log;

    location / {
        limit_req zone=global_limit burst=20 nodelay;

        proxy_pass http://app-go:8080;

        proxy_cache            cache_go;
        proxy_cache_valid      200 10s;
        proxy_cache_use_stale  error timeout updating http_500 http_502 http_503 http_504;
        proxy_cache_lock       on;

        add_header X-Cache-Status $upstream_cache_status always;
        add_header X-Cache-TTL    "10s" always;
        add_header X-App          "app-go" always;
    }

    location /stub_status {
        stub_status;
        allow 127.0.0.0/8;
        allow 172.16.0.0/12;
        allow 10.0.0.0/8;
        deny all;
    }
}

# ─── App Python (cache 1m) ───────────────────────────────
server {
    listen 81;
    server_name localhost;
    server_tokens off;

    # ── Security Headers ──
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-Frame-Options "DENY" always;
    add_header X-XSS-Protection "1; mode=block" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;
    add_header Content-Security-Policy "default-src 'self'" always;

    access_log /var/log/nginx/app_python_access.log cache_log;

    location / {
        limit_req zone=global_limit burst=20 nodelay;

        proxy_pass http://app-python:8081;

        proxy_cache            cache_python;
        proxy_cache_valid      200 1m;
        proxy_cache_use_stale  error timeout updating http_500 http_502 http_503 http_504;
        proxy_cache_lock       on;

        add_header X-Cache-Status $upstream_cache_status always;
        add_header X-Cache-TTL    "60s" always;
        add_header X-App          "app-python" always;
    }
}
